name: FW CI

on: [push, pull_request]

jobs:
  build-firmware:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          sketch-paths: KaN_Gauge/
          libraries: |
            - name: U8g2
              source-url: https://github.com/olikraus/u8g2.git
